Repository msolefonte/vco, pull requests merged in 2022-11, with the labels that each got.

#212 Fix locking & unlocking units generic functions
  src/script/_lib/mod/vco-commons.lua
Labels: bug

#214 Fixes for World Walkers
  docs/immortal-empires/norsca.md
  src/db/building_units_allowed_tables_vco.tsv
  src/db/effect_bonus_value_ids_unit_sets_tables_vco.tsv
  src/db/effect_bonus_value_unit_set_unit_ability_junctions_tables_vco.tsv
  src/db/effect_bundles_to_effects_junctions_tables_vco.tsv
  src/db/effects_tables_vco.tsv
  src/db/frontend_faction_leaders_tables_vco.tsv
  src/db/special_ability_phase_attribute_effects_tables_vco.tsv
  src/db/special_ability_phase_stat_effects_tables_vco.tsv
  src/db/special_ability_phases_tables_vco.tsv
  src/db/special_ability_to_invalid_target_flags_tables_vco.tsv
  src/db/special_ability_to_special_ability_phase_junctions_tables_vco.tsv
  src/db/unit_abilities_tables_vco.tsv
  src/db/unit_set_unit_ability_junctions_tables_vco.tsv
  src/db/unit_special_abilities_tables_vco.tsv
  src/db/vco_effects.loc.tsv
  src/db/vco_special_ability_phases.loc.tsv
  src/db/vco_unit_abilities.loc.tsv
Labels: bug

#220 Updating Aranessa to remove problematic movement range effect
  src/db/effect_bonus_value_ids_unit_sets_tables_vco.tsv
  src/db/effect_bonus_value_unit_set_unit_ability_junctions_tables_vco.tsv
  src/db/effect_bundles_tables_vco.tsv
  src/db/effect_bundles_to_effects_junctions_tables_vco.tsv
  src/db/effects_tables_vco.tsv
  src/db/special_ability_phase_attribute_effects_tables_vco.tsv
  src/db/special_ability_phase_stat_effects_tables_vco.tsv
  src/db/special_ability_phases_tables_vco.tsv
  src/db/special_ability_to_invalid_target_flags_tables_vco.tsv
  src/db/special_ability_to_special_ability_phase_junctions_tables_vco.tsv
  src/db/unit_abilities_tables_vco.tsv
  src/db/unit_set_to_unit_junctions_tables_vco.tsv
  src/db/unit_set_unit_ability_junctions_tables_vco.tsv
  src/db/unit_sets_tables_vco.tsv
  src/db/unit_special_abilities_tables_vco.tsv
  src/db/vco_effect_bundles.loc.tsv
  src/db/vco_effects.loc.tsv
  src/db/vco_mission_text.loc.tsv
  src/db/vco_special_ability_phases.loc.tsv
  src/db/vco_unit_abilities.loc.tsv
  src/db/vco_victory_types.loc.tsv
Labels: bug, remove-on-ready

#234 Fix stuff
  dist/wolfy_vco.pack
  docs/immortal-empires/vampire-coast.md
  src/db/effect_bundles_tables_vco.tsv
  src/db/effect_bundles_to_effects_junctions_tables_vco.tsv
  src/db/effects_tables_vco.tsv
  src/db/vco_effect_bundles.loc.tsv
  src/db/vco_effects.loc.tsv
  src/db/vco_mission_text.loc.tsv
  src/script/_lib/mod/vco-commons.lua
  src/script/campaign/mod/vco-listeners-cst.lua
  src/script/campaign/mod/vco-listeners-kho.lua
  src/script/campaign/mod/vco-listeners-nor.lua
  src/script/vco-ie/main_warhammer/wh2_dlc09_tmb_followers_of_nagash/missions.lua
  src/script/vco-ie/main_warhammer/wh2_dlc11_cst_pirates_of_sartosa/missions.lua
  src/script/vco-ie/main_warhammer/wh2_dlc13_emp_the_huntmarshals_expedition/missions.lua
  src/script/vco-ie/main_warhammer/wh2_main_def_cult_of_pleasure/missions.lua
  src/script/vco-ie/main_warhammer/wh2_main_lzd_hexoatl/missions.lua
  src/script/vco-ie/main_warhammer/wh2_main_skv_clan_moulder/missions.lua
  src/script/vco-ie/main_warhammer/wh3_main_cth_the_northern_provinces/missions.lua
  src/script/vco-ie/main_warhammer/wh3_main_cth_the_western_provinces/missions.lua
  src/script/vco-ie/main_warhammer/wh3_main_ksl_the_great_orthodoxy/missions.lua
  src/script/vco-ie/main_warhammer/wh3_main_ogr_goldtooth/missions.lua
  src/script/vco-ie/main_warhammer/wh_dlc08_nor_norsca/missions.lua
  src/script/vco-ie/main_warhammer/wh_main_brt_bordeleaux/missions.lua
  src/script/vco-ie/main_warhammer/wh_main_grn_greenskins/missions.lua
  src/script/vco-ie/main_warhammer/wh_main_vmp_vampire_counts/missions.lua
Labels: bug, remove-on-ready

#242 Feature: Expanded Great Game mission text table to support 100 regions
  src/db/vco_mission_text.loc.tsv
Labels: remove-on-ready, feature

#243 Update 5.0.0-beta.7.HOTFIX-1
  CHANGELOG.md
  src/db/effects_tables_vco.tsv
  src/db/vco_effects.loc.tsv
  src/script/campaign/mod/vco-listeners-def.lua
  src/script/campaign/mod/vco-listeners-ksl.lua
  src/script/campaign/mod/vco-listeners-nor.lua
  src/ui/campaign ui/effect_bundles/bullet_cst_infamy.png
  src/ui/campaign ui/effect_bundles/military_spending_upkeep.png
  src/ui/campaign ui/effect_bundles/wh2_dlc11_army_abilities_zhufbar_42_pounders.png
  src/ui/campaign ui/effect_bundles/wh2_dlc11_item_abilities_captain_roths_moondial.png
  src/ui/campaign ui/effect_bundles/wh_dlc06_unit_passive_opportunist_murderer.png
  src/ui/campaign ui/effect_bundles/wh_dlc08_lord_abilities_fight_or_die.png
  src/ui/campaign ui/effect_bundles/wh_dlc08_seafang.png
  src/ui/campaign ui/effect_bundles/wh_main_unit_contact_poison.png
  src/ui/campaign ui/effect_bundles/wh_pro04_unit_abilities_enrage.png
Labels: bug

#253 Add design for Grombrindal
  docs/README.md
  docs/immortal-empires/dwarfs.md
Labels: documentation
